# Generated by Django 5.2.4 on 2025-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
